name: Build on push with tag

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3

      - name: Compile Solution (MSBuild)
        run: |
          msbuild MikuMikuWorld.sln /p:Configuration=Release /p:Platform=x64

      - name: Copy Assets and Dependencies
        run: |
          rake build:copy

      - name: Upload Artifact Zip
        uses: actions/upload-artifact@v4
        with:
          name: MikuMikuWorld4CC-Build
          path: ./build/
