name: Build on push with tag

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3

      - name: Install NSIS
        run: choco install nsis -y

      - name: Build
        run: |
          rake build

      - name: Upload Artifact Zip
        uses: actions/upload-artifact@v4
        with:
          name: MikuMikuWorld4CC-Build
          path: ./build/
